apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluxtoolbox
rules:
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - get
  - list
  - patch
---
