apiVersion: v1
kind: Namespace
metadata:
  name: gobg-uat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gobg
  name: gobg
  namespace: gobg-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobg
  strategy: {}
  template:
    metadata:
      labels:
        app: gobg
    spec:
      containers:
      - image: christianh814/gobg:blue
        name: gobg
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gobg
  name: gobg
  namespace: gobg-uat
spec:
  ports:
  - nodePort: 30082
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gobg
  type: NodePort
