apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  verification:
    analysisTemplates:
    - name: flux-reconciler
    args:
    - name: appname
      value: gobg-test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/christianh814/kargo-4-flux
      writeBranch: stage/test
    argoCDAppUpdates: []
