apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  verification:
    analysisTemplates:
    - name: flux-reconciler
    args:
    - name: appname
      value: gobg-uat
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/christianh814/kargo-4-flux
      writeBranch: stage/uat
    argoCDAppUpdates: []
