apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- project.yaml
- serviceaccount-fluxtoolbox.yaml
- clusterrole-fluxtoolbox.yaml
- clusterrolebinding-fluxtoolbox.yaml
- analysistemplate-reconciler.yaml

sortOptions:
  order: fifo
